methods needed:

    -fix _get_obs
    -control joint vy joint
    -read joint by joint
    -fix the order of joints in action space
    -fix the limits of joint on action space TO BE TORQUE

    --phase 2:7
    -reward
    -action
    -step
        -timeout when T is reached



    --phase 1:
    -limit obs space by actual
    

done:
    -print obs
    -update obs infra in init
    -reset
    -_get_obs

    -random bezier parameters
    -random time span
    -update motion selector
    -update current and past states
    -update past 6 actions
    -time progress

In [1]:
import gymnasium as gym
from gymnasium import spaces
import numpy as np

env = gym.make('A1Soccer-v2', render_mode = 'human')

In [2]:
env.action_space.sample()

array([ 0.33362103,  2.8505905 , -2.467269  ,  0.15610287, -0.6517698 ,
       -2.383648  , -0.7163224 ,  1.8749487 , -1.9481026 , -0.42189732,
        2.0172963 , -2.66782   ], dtype=float32)

In [3]:
# spaces.Box(low = env.min_joint_value, high = env.max_joint_value, dtype = np.float32)
# x = spaces.Box(low = env.action_box_low, high = env.action_box_high, dtype = np.float32)
# env.action_box_low, env.action_box_high

In [4]:
env.data.actuator.__doc__
#.__dir__()
# env.data.actuator.()

/Users/mohammedbadra/codes/minerva/capstone/robot-ball-gym/gymnasium-repo/Gymnasium/gymnasium/core.py:297: UserWarning: WARN: env.data to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.data` for environment variables or `env.get_attr('data')` that will search the remaining wrappers.
  logger.warn(


"actuator(*args, **kwargs)\nOverloaded function.\n\n1. actuator(self: mujoco._structs.MjData, arg0: int) -> mujoco::python::MjDataActuatorViews\n\n2. actuator(self: mujoco._structs.MjData, name: str = '') -> mujoco::python::MjDataActuatorViews\n"

In [3]:
env.action_space.sample()

array([ 0.5978266 ,  3.9588478 , -1.3895917 ,  0.79002976, -1.016216  ,
       -2.1037297 , -0.20529164,  2.9303007 , -1.8863648 ,  0.6731029 ,
        0.961458  , -0.97211146], dtype=float32)

In [4]:
# class 

joints = {
    'FR_hip_joint': 0,
    'FR_thigh_joint': 0,
    'FR_calf_joint': 0,
    'FL_hip_joint': 0,
    'FL_thigh_joint': 0,
    'FL_calf_joint': 0,
    'RR_hip_joint': 0,
    'RR_thigh_joint': 0,
    'RR_calf_joint': 0,
    'RL_hip_joint': 0,
    'RL_thigh_joint': 0,
    'RL_calf_joint': 0}

robot_orientation = {"qw": 0, "qx": 0, "qy": 0, "qz":0}

def apply_action(self):


SyntaxError: incomplete input (2409875464.py, line 19)

In [5]:
def mover(self):
    while True:  
        x = env.action_space.sample()
        print("Action:", x)
        env.step(x)

        # print("Actual", env.get_robot_joint_positions())
        print("Ctrl data", env.data.ctrl)
    

        

        time.sleep(0.1)

        # print("OBSERVATION COMING UP")
        # # print(env.update_robot_state())
        # env.print_obs()
        # you can use a random action or some default action
        env.render()

In [13]:
dir(env.data.qpos)

/Users/mohammedbadra/codes/minerva/capstone/robot-ball-gym/gymnasium-repo/Gymnasium/gymnasium/core.py:297: UserWarning: WARN: env.data to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.data` for environment variables or `env.get_attr('data')` that will search the remaining wrappers.
  logger.warn(


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [17]:
env.action_space

Box([-0.802851 -1.0472   -2.69653  -0.802851 -1.0472   -2.69653  -0.802851
 -1.0472   -2.69653  -0.802851 -1.0472   -2.69653 ], [ 0.802851  4.18879  -0.916298  0.802851  4.18879  -0.916298  0.802851
  4.18879  -0.916298  0.802851  4.18879  -0.916298], (12,), float32)

In [18]:
x = env.data.qpos
y = env.data.qvel

x,y

/Users/mohammedbadra/codes/minerva/capstone/robot-ball-gym/gymnasium-repo/Gymnasium/gymnasium/core.py:297: UserWarning: WARN: env.data to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.data` for environment variables or `env.get_attr('data')` that will search the remaining wrappers.
  logger.warn(


(array([ 0.  ,  0.  ,  0.06,  1.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.85,
         0.45,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]))

In [24]:
x.shape, y.shape

((26,), (24,))

In [26]:
len(x)

26

In [53]:
z = [number for number in range(1, 27)]


print(len(z[:7]), len(z[7:19]), len(z[19:]))


(z[:7]), (z[7:19]), (z[19:])

7 12 7


([1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26])

In [34]:
len(x[20:])

6

In [55]:
len(y[:6]), len(y[6:18]), len(y[18:])

(6, 12, 6)

In [57]:
# class Robot_Data:
#     def __init__(self, qpos, qvel):
#         self.trunk_qpos = qpos[:7]
#         self.legs_qpos = qpos[7:19]
#         self.ball_qpos = qpos[19:]

#         self.trunk_qvel = qvel[:6]
#         self.legs_qvel = qvel[6:18]
#         self.ball_qvel = qvel[18:]



        

In [58]:
class RobotState:
    """
        Takes in env.data.qpos and env.data.qvel and processes
        them with labels into:
            -trunk_qpos_dict
            -legs_qpos_dict
            -ball_qpos_dict

            -trunk_qvel_dict
            -legs_qvel_dict
            -ball_qvel_dict
    """
    
    def __init__(self, qpos, qvel):
        # Assuming qpos and qvel are provided as input lists or numpy arrays
        self.trunk_qpos = qpos[:7]
        self.legs_qpos = qpos[7:19]
        self.ball_qpos = qpos[19:]

        self.trunk_qvel = qvel[:6]
        self.legs_qvel = qvel[6:18]
        self.ball_qvel = qvel[18:]


        self.trunk_qpos_dict = self.create_trunk_qpos_dict()
        self.legs_qpos_dict = self.create_legs_qpos_dict()
        self.ball_qpos_dict = self.create_ball_qpos_dict()

        self.trunk_qvel_dict = self.create_trunk_qvel_dict()
        self.legs_qvel_dict = self.create_legs_qvel_dict()
        self.ball_qvel_dict = self.create_ball_qvel_dict()

    def create_trunk_qpos_dict(self):
        trunk_qpos_dict = {
            'trunk_pos_x': self.trunk_qpos[0],
            'trunk_pos_y': self.trunk_qpos[1],
            'trunk_pos_z': self.trunk_qpos[2],
            'trunk_orient_qw': self.trunk_qpos[3],
            'trunk_orient_qx': self.trunk_qpos[4],
            'trunk_orient_qy': self.trunk_qpos[5],
            'trunk_orient_qz': self.trunk_qpos[6]}
        
        return trunk_qpos_dict

    def create_legs_qpos_dict(self):
        leg_names = ['FR', 'FL', 'RR', 'RL']
        joint_names = ['hip_pos', 'thigh_pos', 'calf_pos']
        legs_qpos_dict = {}
        for i, leg in enumerate(leg_names):
            for j, joint in enumerate(joint_names):
                key = f"{leg}_{joint}"
                legs_qpos_dict[key] = self.legs_qpos[i * 3 + j]
        return legs_qpos_dict

    def create_ball_qpos_dict(self):
        ball_qpos_dict =  {
            'ball_pos_x': self.ball_qpos[0],
            'ball_pos_y': self.ball_qpos[1],
            'ball_pos_z': self.ball_qpos[2],
            'ball_orient_qw': self.ball_qpos[3],
            'ball_orient_qx': self.ball_qpos[4],
            'ball_orient_qy': self.ball_qpos[5],
            'ball_orient_qz': self.ball_qpos[6]}
        
        return ball_qpos_dict

    def create_trunk_qvel_dict(self):
        trunk_qvel_dict =  {
            'trunk_vel_x': self.trunk_qvel[0],
            'trunk_vel_y': self.trunk_qvel[1],
            'trunk_vel_z': self.trunk_qvel[2],
            'trunk_angvel_x': self.trunk_qvel[3],
            'trunk_angvel_y': self.trunk_qvel[4],
            'trunk_angvel_z': self.trunk_qvel[5]}
        
        return trunk_qvel_dict

    def create_legs_qvel_dict(self):
        leg_names = ['FR', 'FL', 'RR', 'RL']
        joint_names = ['hip_vel', 'thigh_vel', 'calf_vel']
        legs_qvel_dict = {}
        for i, leg in enumerate(leg_names):
            for j, joint in enumerate(joint_names):
                key = f"{leg}_{joint}"
                legs_qvel_dict[key] = self.legs_qvel[i * 3 + j]

        return legs_qvel_dict

    def create_ball_qvel_dict(self):
        ball_qvel_dict =  {
            'ball_vel_x': self.ball_qvel[0],
            'ball_vel_y': self.ball_qvel[1],
            'ball_vel_z': self.ball_qvel[2],
            'ball_angvel_x': self.ball_qvel[3],
            'ball_angvel_y': self.ball_qvel[4],
            'ball_angvel_z': self.ball_qvel[5]}
        
        return ball_qvel_dict

In [68]:
x = env.data.qpos
y = env.data.qvel

s1 = RobotState(x, y)

s1.trunk_qpos_dict, s1.legs_qpos_dict, s1.ball_qpos_dict

({'trunk_pos_x': 0.0,
  'trunk_pos_y': 0.0,
  'trunk_pos_z': 0.06,
  'trunk_orient_qw': 1.0,
  'trunk_orient_qx': 0.0,
  'trunk_orient_qy': 0.0,
  'trunk_orient_qz': 0.0},
 {'FR_hip_pos': 0.0,
  'FR_thigh_pos': -0.85,
  'FR_calf_pos': 0.45,
  'FL_hip_pos': 1.0,
  'FL_thigh_pos': 0.0,
  'FL_calf_pos': 0.0,
  'RR_hip_pos': 0.0,
  'RR_thigh_pos': 0.0,
  'RR_calf_pos': 0.0,
  'RL_hip_pos': 0.0,
  'RL_thigh_pos': 0.0,
  'RL_calf_pos': 0.0},
 {'ball_pos_x': 0.0,
  'ball_pos_y': 0.0,
  'ball_pos_z': 0.0,
  'ball_orient_qw': 0.0,
  'ball_orient_qx': 0.0,
  'ball_orient_qy': 0.0,
  'ball_orient_qz': 0.0})

observation space update:
    bezier_parameters: 15
        (constant episode)
    motion_phase_time_span: 1
        (constant episode)

need to be updated
    motion_phase_selector: 1
        (updated by update_motion_phase_selector)
    motion_phase_progress: 1
        (updated by update_motion_phase_progress)
    combined_history: 84+21
        ()
    action_history: 72
        ()



observation space retrieval:
    motion_phase_selector: 1 (updated by update_motion_phase_selector)
    bezier_parameters: 15
    motion_phase_time_span: 1
    motion_phase_progress: 1
    combined_robot_state_history: 84+21
    action_history: 72



self.observation_structure = {
    "motion_phase_selector": motion_phase_selector_dim,
    "bezier_parameters": bezier_parameters_dim,
    "motion_phase_time_span": motion_phase_time_span_dim,
    "motion_phase_progress": motion_phase_progress_dim,
    "combined_robot_state_history": combined_history_dim,  # Joint positions and orientation history combined
    "action_history": action_history_dim}









before you get obs, at each step, you n

during each step you do this:
    -update motion phase selector
    -update bezier_parameters
    -update motion_phase_time_span
    -update motion_phase_progress
    -update combined_history
    -update action history

In [74]:
6*12

72

In [4]:
env.RobotState(env.qpos, env.qvel)

/Users/mohammedbadra/codes/minerva/capstone/robot-ball-gym/gymnasium-repo/Gymnasium/gymnasium/core.py:297: UserWarning: WARN: env.RobotState to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.RobotState` for environment variables or `env.get_attr('RobotState')` that will search the remaining wrappers.
  logger.warn(


AttributeError: 'A1SoccerEnv_v2' object has no attribute 'RobotState'

In [3]:
env.print_obs()

motion_phase_selector:
[0.]

bezier_parameters:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

motion_phase_time_span:
[0.]

motion_phase_progress:
[0.]

combined_robot_state_history:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0.]

action_history:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]



/Users/mohammedbadra/codes/minerva/capstone/robot-ball-gym/gymnasium-repo/Gymnasium/gymnasium/core.py:297: UserWarning: WARN: env.print_obs to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.print_obs` for environment variables or `env.get_attr('print_obs')` that will search the remaining wrappers.
  logger.warn(
